language: node_js
node_js:
  - "6.10"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm install -g jest

install:
  - yarn install

before_deploy:
  - npm install -g serverless

deploy:
  provider: script
  script: serverless deploy
  skip_cleanup: true
  on:
    branch: master

